### ISSUE TITLE
how to use REST server

### ISSUE THREAD

**Issue by chunghuihuang** [openbmc/meta-intel#1]
how to use REST server

**Comment by edtanous** [comment]
Have you tried reading the documentation?

**Comment by chunghuihuang** [comment]
yes ,but i cant't use any rest url 
ex: https://${bmc}/xyz/openbmc_project/list

**Comment by edtanous** [comment]
We need more details to help you solve your problem:
What platform are you using?
What version of the webserver are you running? (bmcweb, phosphor-rest, or bmcweb+phosphor-rest+nginx)
What command are you running to test that url?
What error code are you getting?
Have you logged in?

Any detail you can add would help a lot, but as you've written it, it's hard to identify the issue.

**Comment by chunghuihuang** [comment]
I used meta-intel platform.
The webserver is bmcweb+ phosphor-rest+nginx
and i run this command:
./qemu-system-arm -m 256 -M romulus-bmc -nographic -drive file=./obmc-phosphor-image-s2600wf.static.mtd,format=raw,if=mtd -net nic -net user,hostfwd=:127.0.0.1:2222-:22,hostfwd=:127.0.0.1:2443-:443,hostname=qemu

I use Browser to open url:https://localhost:2443 
Response :403 Forbidden

 url:https://localhost:2443/login
response:502 Bad Gateway

i also try metal-intel platform + webserver is bmcweb
then I use phosphor-rest to connect bmcweb is fail.
